### ISSUE TITLE
Running exe problem

### ISSUE THREAD

**Issue by Userrr123** [SamboyCoding/Cpp2IL#3]
When I try to run the exe it instantly crashesh

**Comment by AndnixSH** [comment]
You run this in cmd/powershell, not open directly

![image](https://user-images.githubusercontent.com/40742924/88461222-fee99980-cea1-11ea-91a9-5a35434b58b4.png)

**Comment by Userrr123** [comment]
Oh, ok, ty very much! And one more question... Could you make a tutorial on your website about about this or maybe a Video? It would be great! I really appreciate your work and you teach many people stuff about modding which is really cool!

**Comment by AndnixSH** [comment]
Will do it soon. I'm busy at the moment
Keep in mind, this tool is for PC games only and is working in progress (WIP)
You can close this issue
