### ISSUE TITLE
Are there plans to make it able to reconstruct the IL?

### ISSUE THREAD

**Issue by ludinenzo** [SamboyCoding/Cpp2IL#5]
I know it's a WIP, but is reconstructing the IL one of the planned features for this, or is it out of the scope of the project?

**Comment by SamboyCoding** [comment]
Sorry, I didn't see this issue. Yes, I'm currently rewriting the internals in order to prepare for IL reconstruction.

**Comment by MishaTY** [comment]
Any Update?

**Comment by SamboyCoding** [comment]
I do now have an update for this ticket - the new analysis engine is *roughly* on-par with the old one, so I've enabled it by default. It should allow for IL generation in the (comparatively-)near future.

**Comment by SamboyCoding** [comment]
This is now sort of implemented. There's a new command line option in the dev build, `--experimental-enable-il-to-assembly-please`, which will ATTEMPT to save the IL back to the DLL. You can change which DLL this runs for with `--run-analysis-for-assembly=AssemblyNameWithoutDllExtension`. 

This will be going live in the next milestone release shortly. Probably going to call it 2021.3.1.

**Comment by SamboyCoding** [comment]
Going to close this now as its basically implemented for everything relevant, all else is covered by other stuff in the roadmap and issues
